### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by hseermc** [SlimefunGuguProject/InfinityExpansion#27] opened 2023-11-17 10:56 UTC
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/InfinityExpansion/issues)，且没有找到相同的问题

### 问题描述

服务器后台爆炸了      leaves核心
[15:26:22 ERROR]: [InfinityExpansion] Item "BASIC_STORAGE" from InfinityExpansion vBuild 11 (git f9fe427) has caused an Error!
[15:26:22 ERROR]: [InfinityExpansion] You can report it here: https://github.com/SlimefunGuguProject/InfinityExpansion/issues
[15:26:22 ERROR]: [InfinityExpansion] Could not pass "BlockBreakHandler" for StorageUnit - 'BASIC_STORAGE' (InfinityExpansion vBuild 11 (git f9fe427))
java.lang.IllegalArgumentException: The provided value cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.persistence.CraftPersistentDataContainer.set(CraftPersistentDataContainer.java:39) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at io.github.mooy1.infinityexpansion.items.storage.StorageUnit.saveToStack(StorageUnit.java:214) ~[InfinityExpansion-Build 10 (git 15accb8).jar:?]
        at io.github.mooy1.infinityexpansion.items.storage.StorageCache.destroy(StorageCache.java:257) ~[InfinityExpansion-Build 10 (git 15accb8).jar:?]
        at io.github.mooy1.infinityexpansion.items.storage.StorageUnit$2.onPlayerBreak(StorageUnit.java:116) ~[InfinityExpansion-Build 10 (git 15accb8).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callBlockHandler$3(BlockListener.java:215) ~[Slimefun-54c1294-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:1002) ~[Slimefun-54c1294-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:215) ~[Slimefun-54c1294-Beta.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:188) ~[Slimefun-54c1294-Beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor37.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:392) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:351) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:302) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1830) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:52) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1350) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1434) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 复现步骤

方块变原版

### 预期行为

方块变砖了

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun-54c1294-Beta

### 插件版本

11

**Comment by ybw0014** [comment] 2023-11-17 19:44
Duplicate of #26

**Closed as not planned by ybw0014** 2023-11-17 19:44 UTC
Labels: bug
